// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIoO4RKX6kHfkQUByelPu2iI0eeatgmBI',
    appId: '1:652560963859:android:5a21a606b5dcb7b74362e6',
    messagingSenderId: '652560963859',
    projectId: 'fooddeliveryapplicationdemo',
    storageBucket: 'fooddeliveryapplicationdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98ezG1PJb0id6js5yHHO2Y2NHg2NQKos',
    appId: '1:652560963859:ios:f2498baa38fdbd084362e6',
    messagingSenderId: '652560963859',
    projectId: 'fooddeliveryapplicationdemo',
    storageBucket: 'fooddeliveryapplicationdemo.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkvab_PUP2-ZgAiwJgAGDsPC7282pJd10',
    appId: '1:652560963859:web:b008656ed62a68ef4362e6',
    messagingSenderId: '652560963859',
    projectId: 'fooddeliveryapplicationdemo',
    authDomain: 'fooddeliveryapplicationdemo.firebaseapp.com',
    storageBucket: 'fooddeliveryapplicationdemo.firebasestorage.app',
    measurementId: 'G-8DT958WF3G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA98ezG1PJb0id6js5yHHO2Y2NHg2NQKos',
    appId: '1:652560963859:ios:f2498baa38fdbd084362e6',
    messagingSenderId: '652560963859',
    projectId: 'fooddeliveryapplicationdemo',
    storageBucket: 'fooddeliveryapplicationdemo.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkvab_PUP2-ZgAiwJgAGDsPC7282pJd10',
    appId: '1:652560963859:web:9475ddde75d6e2c94362e6',
    messagingSenderId: '652560963859',
    projectId: 'fooddeliveryapplicationdemo',
    authDomain: 'fooddeliveryapplicationdemo.firebaseapp.com',
    storageBucket: 'fooddeliveryapplicationdemo.firebasestorage.app',
    measurementId: 'G-WG4EHV6XS4',
  );

}